/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_entry (void)
{
  GtkWidget *gestion_entry;
  GtkWidget *fixed1;
  GtkWidget *eventbox4;
  GtkWidget *btn_gest_le;
  GtkWidget *eventbox5;
  GtkWidget *btn_gest_obs;
  GtkWidget *eventbox6;
  GtkWidget *btn_gest_adm;
  GtkWidget *image7;

  gestion_entry = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_entry), _("Gestion"));
  gtk_window_set_position (GTK_WINDOW (gestion_entry), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion_entry), fixed1);
  gtk_container_set_border_width (GTK_CONTAINER (fixed1), 8);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox4, 264, 184);
  gtk_widget_set_size_request (eventbox4, 240, 32);

  btn_gest_le = gtk_button_new_with_mnemonic (_("Gestion des listes electorales "));
  gtk_widget_show (btn_gest_le);
  gtk_container_add (GTK_CONTAINER (eventbox4), btn_gest_le);
  gtk_widget_set_size_request (btn_gest_le, 240, 32);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox5, 264, 240);
  gtk_widget_set_size_request (eventbox5, 240, 29);

  btn_gest_obs = gtk_button_new_with_mnemonic (_("Gestion des observateurs"));
  gtk_widget_show (btn_gest_obs);
  gtk_container_add (GTK_CONTAINER (eventbox5), btn_gest_obs);
  gtk_widget_set_size_request (btn_gest_obs, 240, 29);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox6, 264, 128);
  gtk_widget_set_size_request (eventbox6, 240, 32);

  btn_gest_adm = gtk_button_new_with_mnemonic (_("Gestion Administrateur"));
  gtk_widget_show (btn_gest_adm);
  gtk_container_add (GTK_CONTAINER (eventbox6), btn_gest_adm);
  gtk_widget_set_size_request (btn_gest_adm, 240, 32);

  image7 = create_pixmap (gestion_entry, "dm.png");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed1), image7, 0, 0);
  gtk_widget_set_size_request (image7, 768, 448);

  g_signal_connect ((gpointer) btn_gest_le, "clicked",
                    G_CALLBACK (on_btn_gest_le_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_gest_obs, "clicked",
                    G_CALLBACK (on_btn_gest_obs_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_gest_adm, "clicked",
                    G_CALLBACK (on_btn_gest_adm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_entry, gestion_entry, "gestion_entry");
  GLADE_HOOKUP_OBJECT (gestion_entry, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion_entry, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (gestion_entry, btn_gest_le, "btn_gest_le");
  GLADE_HOOKUP_OBJECT (gestion_entry, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (gestion_entry, btn_gest_obs, "btn_gest_obs");
  GLADE_HOOKUP_OBJECT (gestion_entry, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (gestion_entry, btn_gest_adm, "btn_gest_adm");
  GLADE_HOOKUP_OBJECT (gestion_entry, image7, "image7");

  return gestion_entry;
}

GtkWidget*
create_GE (void)
{
  GtkWidget *GE;
  GtkWidget *fixed2;
  GtkWidget *ge_btn_modif;
  GtkWidget *ge_btn_ajout;
  GtkWidget *ge_btn_supp;
  GtkWidget *ge_btn_aff;

  GE = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GE), _("Gestion des Elections"));
  gtk_window_set_position (GTK_WINDOW (GE), GTK_WIN_POS_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (GE), fixed2);
  gtk_container_set_border_width (GTK_CONTAINER (fixed2), 6);

  ge_btn_modif = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (ge_btn_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), ge_btn_modif, 64, 80);
  gtk_widget_set_size_request (ge_btn_modif, 88, 32);

  ge_btn_ajout = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (ge_btn_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), ge_btn_ajout, 64, 32);
  gtk_widget_set_size_request (ge_btn_ajout, 88, 32);

  ge_btn_supp = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (ge_btn_supp);
  gtk_fixed_put (GTK_FIXED (fixed2), ge_btn_supp, 64, 128);
  gtk_widget_set_size_request (ge_btn_supp, 88, 32);

  ge_btn_aff = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (ge_btn_aff);
  gtk_fixed_put (GTK_FIXED (fixed2), ge_btn_aff, 64, 176);
  gtk_widget_set_size_request (ge_btn_aff, 88, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GE, GE, "GE");
  GLADE_HOOKUP_OBJECT (GE, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (GE, ge_btn_modif, "ge_btn_modif");
  GLADE_HOOKUP_OBJECT (GE, ge_btn_ajout, "ge_btn_ajout");
  GLADE_HOOKUP_OBJECT (GE, ge_btn_supp, "ge_btn_supp");
  GLADE_HOOKUP_OBJECT (GE, ge_btn_aff, "ge_btn_aff");

  return GE;
}

GtkWidget*
create_GE_ajouter (void)
{
  GtkWidget *GE_ajouter;
  GtkWidget *fixed3;
  GtkWidget *entryId;
  GtkWidget *entryNbH;
  GtkObject *spinbutDate_adj;
  GtkWidget *spinbutDate;
  GtkObject *spinbutJour_adj;
  GtkWidget *spinbutJour;
  GtkObject *spinbutAnnee_adj;
  GtkWidget *spinbutAnnee;
  GtkWidget *labelId;
  GtkWidget *labelDate;
  GtkWidget *labelNbH;
  GtkWidget *butQuit;
  GtkWidget *labelMuni;
  GtkWidget *labelNbC;
  GtkWidget *butAjou;
  GtkWidget *comboMuni;
  GtkWidget *radiobutton14;
  GSList *radiobutton14_group = NULL;
  GtkWidget *radiobutton15;
  GtkWidget *radiobutton17;
  GtkWidget *radiobutton19;
  GtkWidget *radiobutton20;
  GtkWidget *radiobutton18;
  GtkWidget *radiobutton16;
  GtkWidget *label67;
  GtkWidget *image9;

  GE_ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GE_ajouter), _("Ajouter"));
  gtk_window_set_position (GTK_WINDOW (GE_ajouter), GTK_WIN_POS_CENTER);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (GE_ajouter), fixed3);
  gtk_container_set_border_width (GTK_CONTAINER (fixed3), 10);

  entryId = gtk_entry_new ();
  gtk_widget_show (entryId);
  gtk_fixed_put (GTK_FIXED (fixed3), entryId, 184, 56);
  gtk_widget_set_size_request (entryId, 150, 32);
  gtk_entry_set_max_length (GTK_ENTRY (entryId), 8);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryId), 8226);

  entryNbH = gtk_entry_new ();
  gtk_widget_show (entryNbH);
  gtk_fixed_put (GTK_FIXED (fixed3), entryNbH, 256, 296);
  gtk_widget_set_size_request (entryNbH, 158, 31);
  gtk_entry_set_max_length (GTK_ENTRY (entryNbH), 7);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNbH), 8226);

  spinbutDate_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutDate = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutDate_adj), 1, 0);
  gtk_widget_show (spinbutDate);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutDate, 232, 120);
  gtk_widget_set_size_request (spinbutDate, 46, 26);

  spinbutJour_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutJour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutJour_adj), 1, 0);
  gtk_widget_show (spinbutJour);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutJour, 304, 120);
  gtk_widget_set_size_request (spinbutJour, 46, 26);

  spinbutAnnee_adj = gtk_adjustment_new (2000, 1922, 2004, 1, 10, 20);
  spinbutAnnee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutAnnee_adj), 1, 0);
  gtk_widget_show (spinbutAnnee);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutAnnee, 376, 120);
  gtk_widget_set_size_request (spinbutAnnee, 62, 26);

  labelId = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (labelId);
  gtk_fixed_put (GTK_FIXED (fixed3), labelId, 74, 56);
  gtk_widget_set_size_request (labelId, 102, 35);

  labelDate = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (labelDate);
  gtk_fixed_put (GTK_FIXED (fixed3), labelDate, 72, 120);
  gtk_widget_set_size_request (labelDate, 140, 37);

  labelNbH = gtk_label_new (_("Nombre d'habitants :"));
  gtk_widget_show (labelNbH);
  gtk_fixed_put (GTK_FIXED (fixed3), labelNbH, 72, 176);
  gtk_widget_set_size_request (labelNbH, 150, 34);

  butQuit = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (butQuit);
  gtk_fixed_put (GTK_FIXED (fixed3), butQuit, 8, 8);
  gtk_widget_set_size_request (butQuit, 48, 26);

  labelMuni = gtk_label_new_with_mnemonic (_("Municipalite :"));
  gtk_widget_show (labelMuni);
  gtk_fixed_put (GTK_FIXED (fixed3), labelMuni, 80, 352);
  gtk_widget_set_size_request (labelMuni, 97, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelMuni), TRUE);

  labelNbC = gtk_label_new (_("Nombre de conseiller :"));
  gtk_widget_show (labelNbC);
  gtk_fixed_put (GTK_FIXED (fixed3), labelNbC, 80, 296);
  gtk_widget_set_size_request (labelNbC, 158, 35);

  butAjou = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (butAjou);
  gtk_fixed_put (GTK_FIXED (fixed3), butAjou, 664, 384);
  gtk_widget_set_size_request (butAjou, 102, 33);

  comboMuni = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboMuni);
  gtk_fixed_put (GTK_FIXED (fixed3), comboMuni, 200, 352);
  gtk_widget_set_size_request (comboMuni, 156, 30);
  gtk_container_set_border_width (GTK_CONTAINER (comboMuni), 2);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboMuni), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboMuni), _("Ariana"));

  radiobutton14 = gtk_radio_button_new_with_mnemonic (NULL, _("Jusqu'a 5000"));
  gtk_widget_show (radiobutton14);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton14, 264, 176);
  gtk_widget_set_size_request (radiobutton14, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton14), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton14));

  radiobutton15 = gtk_radio_button_new_with_mnemonic (NULL, _("de 5001 a 10000"));
  gtk_widget_show (radiobutton15);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton15, 424, 176);
  gtk_widget_set_size_request (radiobutton15, 134, 26);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton15), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton15));

  radiobutton17 = gtk_radio_button_new_with_mnemonic (NULL, _("de 10.001 a 25000"));
  gtk_widget_show (radiobutton17);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton17, 584, 176);
  gtk_widget_set_size_request (radiobutton17, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton17), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton17));

  radiobutton19 = gtk_radio_button_new_with_mnemonic (NULL, _("de 100.001 a 500.000"));
  gtk_widget_show (radiobutton19);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton19, 584, 200);
  gtk_widget_set_size_request (radiobutton19, 166, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton19), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton19));

  radiobutton20 = gtk_radio_button_new_with_mnemonic (NULL, _("plus de 500.000"));
  gtk_widget_show (radiobutton20);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton20, 264, 224);
  gtk_widget_set_size_request (radiobutton20, 142, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton20), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton20));

  radiobutton18 = gtk_radio_button_new_with_mnemonic (NULL, _("de 25.001 a 50000"));
  gtk_widget_show (radiobutton18);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton18, 264, 200);
  gtk_widget_set_size_request (radiobutton18, 150, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton18), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton18));

  radiobutton16 = gtk_radio_button_new_with_mnemonic (NULL, _("de 50.001 a 100.000"));
  gtk_widget_show (radiobutton16);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton16, 424, 200);
  gtk_widget_set_size_request (radiobutton16, 158, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton16), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton16));

  label67 = gtk_label_new (_("Ajouter une election\n"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed3), label67, 280, 8);
  gtk_widget_set_size_request (label67, 190, 22);

  image9 = create_pixmap (GE_ajouter, "23BMVOTERSLIST.jpg");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed3), image9, 0, 448);
  gtk_widget_set_size_request (image9, 784, 176);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GE_ajouter, GE_ajouter, "GE_ajouter");
  GLADE_HOOKUP_OBJECT (GE_ajouter, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (GE_ajouter, entryId, "entryId");
  GLADE_HOOKUP_OBJECT (GE_ajouter, entryNbH, "entryNbH");
  GLADE_HOOKUP_OBJECT (GE_ajouter, spinbutDate, "spinbutDate");
  GLADE_HOOKUP_OBJECT (GE_ajouter, spinbutJour, "spinbutJour");
  GLADE_HOOKUP_OBJECT (GE_ajouter, spinbutAnnee, "spinbutAnnee");
  GLADE_HOOKUP_OBJECT (GE_ajouter, labelId, "labelId");
  GLADE_HOOKUP_OBJECT (GE_ajouter, labelDate, "labelDate");
  GLADE_HOOKUP_OBJECT (GE_ajouter, labelNbH, "labelNbH");
  GLADE_HOOKUP_OBJECT (GE_ajouter, butQuit, "butQuit");
  GLADE_HOOKUP_OBJECT (GE_ajouter, labelMuni, "labelMuni");
  GLADE_HOOKUP_OBJECT (GE_ajouter, labelNbC, "labelNbC");
  GLADE_HOOKUP_OBJECT (GE_ajouter, butAjou, "butAjou");
  GLADE_HOOKUP_OBJECT (GE_ajouter, comboMuni, "comboMuni");
  GLADE_HOOKUP_OBJECT (GE_ajouter, radiobutton14, "radiobutton14");
  GLADE_HOOKUP_OBJECT (GE_ajouter, radiobutton15, "radiobutton15");
  GLADE_HOOKUP_OBJECT (GE_ajouter, radiobutton17, "radiobutton17");
  GLADE_HOOKUP_OBJECT (GE_ajouter, radiobutton19, "radiobutton19");
  GLADE_HOOKUP_OBJECT (GE_ajouter, radiobutton20, "radiobutton20");
  GLADE_HOOKUP_OBJECT (GE_ajouter, radiobutton18, "radiobutton18");
  GLADE_HOOKUP_OBJECT (GE_ajouter, radiobutton16, "radiobutton16");
  GLADE_HOOKUP_OBJECT (GE_ajouter, label67, "label67");
  GLADE_HOOKUP_OBJECT (GE_ajouter, image9, "image9");

  return GE_ajouter;
}

GtkWidget*
create_bv (void)
{
  GtkWidget *bv;
  GtkWidget *fixed4;
  GtkWidget *bv_afficher;
  GtkWidget *bv_modifier;
  GtkWidget *bv_ajout;
  GtkWidget *bv_supprimer;

  bv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (bv), _("Getion bv"));
  gtk_window_set_position (GTK_WINDOW (bv), GTK_WIN_POS_CENTER);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (bv), fixed4);

  bv_afficher = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (bv_afficher);
  gtk_fixed_put (GTK_FIXED (fixed4), bv_afficher, 56, 168);
  gtk_widget_set_size_request (bv_afficher, 120, 40);

  bv_modifier = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (bv_modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), bv_modifier, 56, 216);
  gtk_widget_set_size_request (bv_modifier, 120, 40);

  bv_ajout = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (bv_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), bv_ajout, 56, 64);
  gtk_widget_set_size_request (bv_ajout, 120, 40);

  bv_supprimer = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (bv_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), bv_supprimer, 56, 120);
  gtk_widget_set_size_request (bv_supprimer, 120, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bv, bv, "bv");
  GLADE_HOOKUP_OBJECT (bv, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (bv, bv_afficher, "bv_afficher");
  GLADE_HOOKUP_OBJECT (bv, bv_modifier, "bv_modifier");
  GLADE_HOOKUP_OBJECT (bv, bv_ajout, "bv_ajout");
  GLADE_HOOKUP_OBJECT (bv, bv_supprimer, "bv_supprimer");

  return bv;
}

GtkWidget*
create_bv_ajout (void)
{
  GtkWidget *bv_ajout;
  GtkWidget *fixed5;
  GtkWidget *label1;
  GtkWidget *bv_ajoutId;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkObject *bv_spin1_adj;
  GtkWidget *bv_spin1;
  GtkWidget *label4;
  GtkWidget *bv_radio1;
  GSList *bv_radio1_group = NULL;
  GtkWidget *bv_radio4;
  GtkWidget *label5;
  GtkWidget *bv_adresse;
  GtkWidget *label6;
  GtkWidget *bv_radio2;
  GtkWidget *bv_radio3;
  GtkObject *bv_salle_spin_adj;
  GtkWidget *bv_salle_spin;
  GtkWidget *eventbox1;
  GtkWidget *image6;
  GtkWidget *label7;
  GtkWidget *bv_id;
  GtkWidget *bv_ajout_retour;
  GtkWidget *image13;
  GtkWidget *bv_ajout_addbtn;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image14;
  GtkWidget *label325;

  bv_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (bv_ajout), _("Ajout BV"));
  gtk_window_set_position (GTK_WINDOW (bv_ajout), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (bv_ajout), fixed5);

  label1 = gtk_label_new (_("ajouter un nouveau bureau de vote"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed5), label1, 120, 8);
  gtk_widget_set_size_request (label1, 248, 32);

  bv_ajoutId = gtk_entry_new ();
  gtk_widget_show (bv_ajoutId);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_ajoutId, 176, 96);
  gtk_widget_set_size_request (bv_ajoutId, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (bv_ajoutId), 8226);

  label2 = gtk_label_new (_("Id :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed5), label2, 8, 96);
  gtk_widget_set_size_request (label2, 64, 24);

  label3 = gtk_label_new (_("capacit\303\251 \303\251lecteurs:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed5), label3, 16, 152);
  gtk_widget_set_size_request (label3, 152, 32);

  bv_spin1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  bv_spin1 = gtk_spin_button_new (GTK_ADJUSTMENT (bv_spin1_adj), 1, 0);
  gtk_widget_show (bv_spin1);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_spin1, 176, 152);
  gtk_widget_set_size_request (bv_spin1, 60, 27);

  label4 = gtk_label_new (_("capacit\303\251 observateurs:"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed5), label4, 24, 208);
  gtk_widget_set_size_request (label4, 160, 32);

  bv_radio1 = gtk_radio_button_new_with_mnemonic (NULL, _("1"));
  gtk_widget_show (bv_radio1);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_radio1, 192, 208);
  gtk_widget_set_size_request (bv_radio1, 48, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (bv_radio1), bv_radio1_group);
  bv_radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (bv_radio1));

  bv_radio4 = gtk_radio_button_new_with_mnemonic (NULL, _("4"));
  gtk_widget_show (bv_radio4);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_radio4, 368, 208);
  gtk_widget_set_size_request (bv_radio4, 56, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (bv_radio4), bv_radio1_group);
  bv_radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (bv_radio4));

  label5 = gtk_label_new (_("Adresse :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed5), label5, 8, 272);
  gtk_widget_set_size_request (label5, 104, 24);

  bv_adresse = gtk_entry_new ();
  gtk_widget_show (bv_adresse);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_adresse, 176, 272);
  gtk_widget_set_size_request (bv_adresse, 240, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (bv_adresse), 8226);

  label6 = gtk_label_new (_("Id d'agent :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed5), label6, 8, 336);
  gtk_widget_set_size_request (label6, 112, 24);

  bv_radio2 = gtk_radio_button_new_with_mnemonic (NULL, _("2"));
  gtk_widget_show (bv_radio2);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_radio2, 248, 208);
  gtk_widget_set_size_request (bv_radio2, 56, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (bv_radio2), bv_radio1_group);
  bv_radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (bv_radio2));

  bv_radio3 = gtk_radio_button_new_with_mnemonic (NULL, _("3"));
  gtk_widget_show (bv_radio3);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_radio3, 304, 208);
  gtk_widget_set_size_request (bv_radio3, 64, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (bv_radio3), bv_radio1_group);
  bv_radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (bv_radio3));

  bv_salle_spin_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  bv_salle_spin = gtk_spin_button_new (GTK_ADJUSTMENT (bv_salle_spin_adj), 1, 0);
  gtk_widget_show (bv_salle_spin);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_salle_spin, 176, 392);
  gtk_widget_set_size_request (bv_salle_spin, 192, 32);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox1, 96, 496);
  gtk_widget_set_size_request (eventbox1, 304, 144);

  image6 = create_pixmap (bv_ajout, "bv.png");
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (eventbox1), image6);
  gtk_widget_set_size_request (image6, 304, 144);

  label7 = gtk_label_new (_("Salle :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 0, 392);
  gtk_widget_set_size_request (label7, 96, 32);

  bv_id = gtk_combo_box_entry_new_text ();
  gtk_widget_show (bv_id);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_id, 176, 336);
  gtk_widget_set_size_request (bv_id, 189, 29);

  bv_ajout_retour = gtk_button_new ();
  gtk_widget_show (bv_ajout_retour);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_ajout_retour, 16, 16);
  gtk_widget_set_size_request (bv_ajout_retour, 48, 24);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (bv_ajout_retour), image13);

  bv_ajout_addbtn = gtk_button_new ();
  gtk_widget_show (bv_ajout_addbtn);
  gtk_fixed_put (GTK_FIXED (fixed5), bv_ajout_addbtn, 192, 448);
  gtk_widget_set_size_request (bv_ajout_addbtn, 120, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (bv_ajout_addbtn), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox1), image14, FALSE, FALSE, 0);

  label325 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label325);
  gtk_box_pack_start (GTK_BOX (hbox1), label325, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bv_ajout_addbtn, "clicked",
                    G_CALLBACK (on_bv_ajout_addbtn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bv_ajout, bv_ajout, "bv_ajout");
  GLADE_HOOKUP_OBJECT (bv_ajout, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (bv_ajout, label1, "label1");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_ajoutId, "bv_ajoutId");
  GLADE_HOOKUP_OBJECT (bv_ajout, label2, "label2");
  GLADE_HOOKUP_OBJECT (bv_ajout, label3, "label3");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_spin1, "bv_spin1");
  GLADE_HOOKUP_OBJECT (bv_ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_radio1, "bv_radio1");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_radio4, "bv_radio4");
  GLADE_HOOKUP_OBJECT (bv_ajout, label5, "label5");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_adresse, "bv_adresse");
  GLADE_HOOKUP_OBJECT (bv_ajout, label6, "label6");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_radio2, "bv_radio2");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_radio3, "bv_radio3");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_salle_spin, "bv_salle_spin");
  GLADE_HOOKUP_OBJECT (bv_ajout, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (bv_ajout, image6, "image6");
  GLADE_HOOKUP_OBJECT (bv_ajout, label7, "label7");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_id, "bv_id");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_ajout_retour, "bv_ajout_retour");
  GLADE_HOOKUP_OBJECT (bv_ajout, image13, "image13");
  GLADE_HOOKUP_OBJECT (bv_ajout, bv_ajout_addbtn, "bv_ajout_addbtn");
  GLADE_HOOKUP_OBJECT (bv_ajout, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (bv_ajout, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (bv_ajout, image14, "image14");
  GLADE_HOOKUP_OBJECT (bv_ajout, label325, "label325");

  return bv_ajout;
}

GtkWidget*
create_bv_supprimer (void)
{
  GtkWidget *bv_supprimer;
  GtkWidget *fixed6;
  GtkWidget *bv_inp_supprimer;
  GtkWidget *label9;
  GtkWidget *bv_supprimer_retour;
  GtkWidget *label8;
  GtkWidget *bv_button_supprimer;
  GtkWidget *image10;

  bv_supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (bv_supprimer), _("window4"));
  gtk_window_set_position (GTK_WINDOW (bv_supprimer), GTK_WIN_POS_CENTER);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (bv_supprimer), fixed6);

  bv_inp_supprimer = gtk_entry_new ();
  gtk_widget_show (bv_inp_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), bv_inp_supprimer, 144, 56);
  gtk_widget_set_size_request (bv_inp_supprimer, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (bv_inp_supprimer), 8226);

  label9 = gtk_label_new (_("supprimer un bureau de vote"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed6), label9, 88, 8);
  gtk_widget_set_size_request (label9, 256, 32);

  bv_supprimer_retour = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (bv_supprimer_retour);
  gtk_fixed_put (GTK_FIXED (fixed6), bv_supprimer_retour, 16, 8);
  gtk_widget_set_size_request (bv_supprimer_retour, 48, 24);

  label8 = gtk_label_new (_("Id "));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed6), label8, 48, 56);
  gtk_widget_set_size_request (label8, 96, 32);

  bv_button_supprimer = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (bv_button_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), bv_button_supprimer, 208, 96);
  gtk_widget_set_size_request (bv_button_supprimer, 98, 29);

  image10 = create_pixmap (bv_supprimer, "delete.png");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed6), image10, 344, 0);
  gtk_widget_set_size_request (image10, 176, 152);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bv_supprimer, bv_supprimer, "bv_supprimer");
  GLADE_HOOKUP_OBJECT (bv_supprimer, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (bv_supprimer, bv_inp_supprimer, "bv_inp_supprimer");
  GLADE_HOOKUP_OBJECT (bv_supprimer, label9, "label9");
  GLADE_HOOKUP_OBJECT (bv_supprimer, bv_supprimer_retour, "bv_supprimer_retour");
  GLADE_HOOKUP_OBJECT (bv_supprimer, label8, "label8");
  GLADE_HOOKUP_OBJECT (bv_supprimer, bv_button_supprimer, "bv_button_supprimer");
  GLADE_HOOKUP_OBJECT (bv_supprimer, image10, "image10");

  return bv_supprimer;
}

GtkWidget*
create_bv_modifier (void)
{
  GtkWidget *bv_modifier;
  GtkWidget *fixed7;
  GtkWidget *label10;
  GtkWidget *bv_inp_modifier;
  GtkWidget *bv_modifier_retour;
  GtkWidget *label11;
  GtkWidget *bv_button_modifier;

  bv_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (bv_modifier), _("window5"));
  gtk_window_set_position (GTK_WINDOW (bv_modifier), GTK_WIN_POS_CENTER);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (bv_modifier), fixed7);

  label10 = gtk_label_new (_("modifier un bureau de vote"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed7), label10, 104, 8);
  gtk_widget_set_size_request (label10, 240, 24);

  bv_inp_modifier = gtk_entry_new ();
  gtk_widget_show (bv_inp_modifier);
  gtk_fixed_put (GTK_FIXED (fixed7), bv_inp_modifier, 136, 64);
  gtk_widget_set_size_request (bv_inp_modifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (bv_inp_modifier), 8226);

  bv_modifier_retour = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (bv_modifier_retour);
  gtk_fixed_put (GTK_FIXED (fixed7), bv_modifier_retour, 8, 8);
  gtk_widget_set_size_request (bv_modifier_retour, 56, 24);

  label11 = gtk_label_new (_("Id :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed7), label11, 64, 64);
  gtk_widget_set_size_request (label11, 56, 24);

  bv_button_modifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (bv_button_modifier);
  gtk_fixed_put (GTK_FIXED (fixed7), bv_button_modifier, 184, 104);
  gtk_widget_set_size_request (bv_button_modifier, 104, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bv_modifier, bv_modifier, "bv_modifier");
  GLADE_HOOKUP_OBJECT (bv_modifier, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (bv_modifier, label10, "label10");
  GLADE_HOOKUP_OBJECT (bv_modifier, bv_inp_modifier, "bv_inp_modifier");
  GLADE_HOOKUP_OBJECT (bv_modifier, bv_modifier_retour, "bv_modifier_retour");
  GLADE_HOOKUP_OBJECT (bv_modifier, label11, "label11");
  GLADE_HOOKUP_OBJECT (bv_modifier, bv_button_modifier, "bv_button_modifier");

  return bv_modifier;
}

GtkWidget*
create_bv_affichage (void)
{
  GtkWidget *bv_affichage;
  GtkWidget *fixed34;
  GtkWidget *bv_aff_treev;
  GtkWidget *bv_aff_search;
  GtkWidget *bv_btn_search;
  GtkWidget *bv_aff_btn_ret;

  bv_affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (bv_affichage), _("Affichage"));
  gtk_window_set_position (GTK_WINDOW (bv_affichage), GTK_WIN_POS_CENTER);

  fixed34 = gtk_fixed_new ();
  gtk_widget_show (fixed34);
  gtk_container_add (GTK_CONTAINER (bv_affichage), fixed34);

  bv_aff_treev = gtk_tree_view_new ();
  gtk_widget_show (bv_aff_treev);
  gtk_fixed_put (GTK_FIXED (fixed34), bv_aff_treev, 24, 72);
  gtk_widget_set_size_request (bv_aff_treev, 520, 192);

  bv_aff_search = gtk_entry_new ();
  gtk_widget_show (bv_aff_search);
  gtk_fixed_put (GTK_FIXED (fixed34), bv_aff_search, 160, 24);
  gtk_widget_set_size_request (bv_aff_search, 240, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (bv_aff_search), 8226);

  bv_btn_search = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (bv_btn_search);
  gtk_fixed_put (GTK_FIXED (fixed34), bv_btn_search, 416, 24);
  gtk_widget_set_size_request (bv_btn_search, 74, 29);

  bv_aff_btn_ret = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (bv_aff_btn_ret);
  gtk_fixed_put (GTK_FIXED (fixed34), bv_aff_btn_ret, 24, 24);
  gtk_widget_set_size_request (bv_aff_btn_ret, 74, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bv_affichage, bv_affichage, "bv_affichage");
  GLADE_HOOKUP_OBJECT (bv_affichage, fixed34, "fixed34");
  GLADE_HOOKUP_OBJECT (bv_affichage, bv_aff_treev, "bv_aff_treev");
  GLADE_HOOKUP_OBJECT (bv_affichage, bv_aff_search, "bv_aff_search");
  GLADE_HOOKUP_OBJECT (bv_affichage, bv_btn_search, "bv_btn_search");
  GLADE_HOOKUP_OBJECT (bv_affichage, bv_aff_btn_ret, "bv_aff_btn_ret");

  return bv_affichage;
}

GtkWidget*
create_le (void)
{
  GtkWidget *le;
  GtkWidget *eventbox10;
  GtkWidget *fixed9;
  GtkWidget *image5;
  GtkWidget *label72;
  GtkWidget *le_btn_vote;
  GtkWidget *le_btn_aj;
  GtkWidget *le_btn_supp;
  GtkWidget *le_btn_aff;
  GtkWidget *le_btn_modif;

  le = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (le), _("Gestion Listes electorales"));
  gtk_window_set_position (GTK_WINDOW (le), GTK_WIN_POS_CENTER);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_container_add (GTK_CONTAINER (le), eventbox10);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (eventbox10), fixed9);

  image5 = create_pixmap (le, "Elections_2020.jpg");
  gtk_widget_show (image5);
  gtk_fixed_put (GTK_FIXED (fixed9), image5, 48, 16);
  gtk_widget_set_size_request (image5, 133, 128);

  label72 = gtk_label_new (_("Oubien :"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed9), label72, 24, 216);
  gtk_widget_set_size_request (label72, 184, 25);

  le_btn_vote = gtk_button_new_with_mnemonic (_("Votez"));
  gtk_widget_show (le_btn_vote);
  gtk_fixed_put (GTK_FIXED (fixed9), le_btn_vote, 16, 160);
  gtk_widget_set_size_request (le_btn_vote, 200, 32);

  le_btn_aj = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (le_btn_aj);
  gtk_fixed_put (GTK_FIXED (fixed9), le_btn_aj, 56, 256);
  gtk_widget_set_size_request (le_btn_aj, 120, 40);

  le_btn_supp = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (le_btn_supp);
  gtk_fixed_put (GTK_FIXED (fixed9), le_btn_supp, 56, 304);
  gtk_widget_set_size_request (le_btn_supp, 120, 40);

  le_btn_aff = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (le_btn_aff);
  gtk_fixed_put (GTK_FIXED (fixed9), le_btn_aff, 56, 352);
  gtk_widget_set_size_request (le_btn_aff, 120, 40);

  le_btn_modif = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (le_btn_modif);
  gtk_fixed_put (GTK_FIXED (fixed9), le_btn_modif, 56, 400);
  gtk_widget_set_size_request (le_btn_modif, 120, 40);

  g_signal_connect ((gpointer) le_btn_vote, "clicked",
                    G_CALLBACK (on_le_btn_vote_clicked),
                    NULL);
  g_signal_connect ((gpointer) le_btn_aj, "clicked",
                    G_CALLBACK (on_le_btn_aj_clicked),
                    NULL);
  g_signal_connect ((gpointer) le_btn_supp, "clicked",
                    G_CALLBACK (on_le_btn_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) le_btn_aff, "clicked",
                    G_CALLBACK (on_le_btn_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) le_btn_modif, "clicked",
                    G_CALLBACK (on_le_btn_modif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (le, le, "le");
  GLADE_HOOKUP_OBJECT (le, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (le, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (le, image5, "image5");
  GLADE_HOOKUP_OBJECT (le, label72, "label72");
  GLADE_HOOKUP_OBJECT (le, le_btn_vote, "le_btn_vote");
  GLADE_HOOKUP_OBJECT (le, le_btn_aj, "le_btn_aj");
  GLADE_HOOKUP_OBJECT (le, le_btn_supp, "le_btn_supp");
  GLADE_HOOKUP_OBJECT (le, le_btn_aff, "le_btn_aff");
  GLADE_HOOKUP_OBJECT (le, le_btn_modif, "le_btn_modif");

  return le;
}

GtkWidget*
create_le_ajout (void)
{
  GtkWidget *le_ajout;
  GtkWidget *fixed10;
  GtkWidget *le_ajout_id;
  GtkObject *le_ajout_date_jour_adj;
  GtkWidget *le_ajout_date_jour;
  GtkObject *le_ajout_date_mois_adj;
  GtkWidget *le_ajout_date_mois;
  GtkObject *le_ajout_date_an_adj;
  GtkWidget *le_ajout_date_an;
  GtkWidget *le_ajout_cand1;
  GtkWidget *le_ajout_cand2;
  GtkWidget *le_ajout_cand3;
  GtkWidget *le_ajout_ret_btn;
  GtkWidget *le_ajout_id_tete;
  GtkWidget *label17;
  GtkWidget *label16;
  GtkWidget *label15;
  GtkWidget *label70;
  GtkWidget *label71;
  GtkWidget *label14;
  GtkWidget *image1;
  GtkWidget *le_ajout_or3;
  GSList *le_ajout_or3_group = NULL;
  GtkWidget *label324;
  GtkWidget *le_ajout_or1;
  GtkWidget *le_ajout_or2;
  GtkWidget *le_ajout_robot;
  GtkWidget *le_ajout_addbtn;
  GtkWidget *le_ajout_nbre_candidats;

  le_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (le_ajout), _("Ajout"));
  gtk_window_set_position (GTK_WINDOW (le_ajout), GTK_WIN_POS_CENTER);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (le_ajout), fixed10);

  le_ajout_id = gtk_entry_new ();
  gtk_widget_show (le_ajout_id);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_id, 152, 72);
  gtk_widget_set_size_request (le_ajout_id, 224, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (le_ajout_id), 8226);

  le_ajout_date_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  le_ajout_date_jour = gtk_spin_button_new (GTK_ADJUSTMENT (le_ajout_date_jour_adj), 1, 0);
  gtk_widget_show (le_ajout_date_jour);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_date_jour, 152, 152);
  gtk_widget_set_size_request (le_ajout_date_jour, 48, 24);

  le_ajout_date_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  le_ajout_date_mois = gtk_spin_button_new (GTK_ADJUSTMENT (le_ajout_date_mois_adj), 1, 0);
  gtk_widget_show (le_ajout_date_mois);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_date_mois, 232, 152);
  gtk_widget_set_size_request (le_ajout_date_mois, 48, 24);

  le_ajout_date_an_adj = gtk_adjustment_new (2000, 1922, 2004, 1, 10, 20);
  le_ajout_date_an = gtk_spin_button_new (GTK_ADJUSTMENT (le_ajout_date_an_adj), 1, 0);
  gtk_widget_show (le_ajout_date_an);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_date_an, 312, 152);
  gtk_widget_set_size_request (le_ajout_date_an, 60, 24);

  le_ajout_cand1 = gtk_entry_new ();
  gtk_widget_show (le_ajout_cand1);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_cand1, 224, 232);
  gtk_widget_set_size_request (le_ajout_cand1, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (le_ajout_cand1), 8226);

  le_ajout_cand2 = gtk_entry_new ();
  gtk_widget_show (le_ajout_cand2);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_cand2, 224, 264);
  gtk_widget_set_size_request (le_ajout_cand2, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (le_ajout_cand2), 8226);

  le_ajout_cand3 = gtk_entry_new ();
  gtk_widget_show (le_ajout_cand3);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_cand3, 224, 296);
  gtk_widget_set_size_request (le_ajout_cand3, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (le_ajout_cand3), 8226);

  le_ajout_ret_btn = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (le_ajout_ret_btn);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_ret_btn, 0, 0);
  gtk_widget_set_size_request (le_ajout_ret_btn, 40, 32);

  le_ajout_id_tete = gtk_entry_new ();
  gtk_widget_show (le_ajout_id_tete);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_id_tete, 152, 40);
  gtk_widget_set_size_request (le_ajout_id_tete, 224, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (le_ajout_id_tete), 8226);

  label17 = gtk_label_new (_("Identifiants des candidats :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed10), label17, 24, 232);
  gtk_widget_set_size_request (label17, 200, 24);

  label16 = gtk_label_new (_("Nbre candidats"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed10), label16, 24, 192);
  gtk_widget_set_size_request (label16, 120, 24);

  label15 = gtk_label_new (_("Date"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed10), label15, 88, 152);
  gtk_widget_set_size_request (label15, 49, 17);

  label70 = gtk_label_new (_("Id"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed10), label70, 48, 72);
  gtk_widget_set_size_request (label70, 112, 24);

  label71 = gtk_label_new (_("Id Tete"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed10), label71, 80, 48);
  gtk_widget_set_size_request (label71, 72, 16);

  label14 = gtk_label_new (_("Orientation"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed10), label14, 40, 112);
  gtk_widget_set_size_request (label14, 112, 24);

  image1 = create_pixmap (le_ajout, "voteimg.jpg");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed10), image1, 400, 0);
  gtk_widget_set_size_request (image1, 280, 424);

  le_ajout_or3 = gtk_radio_button_new_with_mnemonic (NULL, _("Droite"));
  gtk_widget_show (le_ajout_or3);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_or3, 312, 112);
  gtk_widget_set_size_request (le_ajout_or3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (le_ajout_or3), le_ajout_or3_group);
  le_ajout_or3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (le_ajout_or3));

  label324 = gtk_label_new (_("Ajouter une Liste electorale"));
  gtk_widget_show (label324);
  gtk_fixed_put (GTK_FIXED (fixed10), label324, 152, 8);
  gtk_widget_set_size_request (label324, 201, 17);

  le_ajout_or1 = gtk_radio_button_new_with_mnemonic (NULL, _("Gauche"));
  gtk_widget_show (le_ajout_or1);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_or1, 152, 112);
  gtk_widget_set_size_request (le_ajout_or1, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (le_ajout_or1), le_ajout_or3_group);
  le_ajout_or3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (le_ajout_or1));

  le_ajout_or2 = gtk_radio_button_new_with_mnemonic (NULL, _("Centre"));
  gtk_widget_show (le_ajout_or2);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_or2, 232, 112);
  gtk_widget_set_size_request (le_ajout_or2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (le_ajout_or2), le_ajout_or3_group);
  le_ajout_or3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (le_ajout_or2));

  le_ajout_robot = gtk_check_button_new_with_mnemonic (_("Je ne suis pas un robot"));
  gtk_widget_show (le_ajout_robot);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_robot, 88, 376);
  gtk_widget_set_size_request (le_ajout_robot, 192, 24);

  le_ajout_addbtn = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_show (le_ajout_addbtn);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_addbtn, 288, 368);
  gtk_widget_set_size_request (le_ajout_addbtn, 88, 37);

  le_ajout_nbre_candidats = gtk_combo_box_new_text ();
  gtk_widget_show (le_ajout_nbre_candidats);
  gtk_fixed_put (GTK_FIXED (fixed10), le_ajout_nbre_candidats, 152, 192);
  gtk_widget_set_size_request (le_ajout_nbre_candidats, 232, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (le_ajout_nbre_candidats), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (le_ajout_nbre_candidats), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (le_ajout_nbre_candidats), _("3"));

  g_signal_connect ((gpointer) le_ajout_addbtn, "clicked",
                    G_CALLBACK (on_le_ajout_btn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (le_ajout, le_ajout, "le_ajout");
  GLADE_HOOKUP_OBJECT (le_ajout, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_id, "le_ajout_id");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_date_jour, "le_ajout_date_jour");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_date_mois, "le_ajout_date_mois");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_date_an, "le_ajout_date_an");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_cand1, "le_ajout_cand1");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_cand2, "le_ajout_cand2");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_cand3, "le_ajout_cand3");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_ret_btn, "le_ajout_ret_btn");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_id_tete, "le_ajout_id_tete");
  GLADE_HOOKUP_OBJECT (le_ajout, label17, "label17");
  GLADE_HOOKUP_OBJECT (le_ajout, label16, "label16");
  GLADE_HOOKUP_OBJECT (le_ajout, label15, "label15");
  GLADE_HOOKUP_OBJECT (le_ajout, label70, "label70");
  GLADE_HOOKUP_OBJECT (le_ajout, label71, "label71");
  GLADE_HOOKUP_OBJECT (le_ajout, label14, "label14");
  GLADE_HOOKUP_OBJECT (le_ajout, image1, "image1");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_or3, "le_ajout_or3");
  GLADE_HOOKUP_OBJECT (le_ajout, label324, "label324");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_or1, "le_ajout_or1");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_or2, "le_ajout_or2");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_robot, "le_ajout_robot");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_addbtn, "le_ajout_addbtn");
  GLADE_HOOKUP_OBJECT (le_ajout, le_ajout_nbre_candidats, "le_ajout_nbre_candidats");

  return le_ajout;
}

GtkWidget*
create_le_supprimer (void)
{
  GtkWidget *le_supprimer;
  GtkWidget *fixed16;
  GtkWidget *label24;
  GtkWidget *label23;
  GtkWidget *le_supp_ret_btn;
  GtkWidget *le_supp_combo;
  GtkWidget *image2;
  GtkWidget *le_btn_supp;

  le_supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (le_supprimer), _("Supression"));
  gtk_window_set_position (GTK_WINDOW (le_supprimer), GTK_WIN_POS_CENTER);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (le_supprimer), fixed16);

  label24 = gtk_label_new (_("Id "));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed16), label24, 64, 64);
  gtk_widget_set_size_request (label24, 56, 24);

  label23 = gtk_label_new (_("supprimer une liste electorale"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed16), label23, 104, 8);
  gtk_widget_set_size_request (label23, 240, 24);

  le_supp_ret_btn = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (le_supp_ret_btn);
  gtk_fixed_put (GTK_FIXED (fixed16), le_supp_ret_btn, 8, 8);
  gtk_widget_set_size_request (le_supp_ret_btn, 56, 24);

  le_supp_combo = gtk_combo_box_entry_new_text ();
  gtk_widget_show (le_supp_combo);
  gtk_fixed_put (GTK_FIXED (fixed16), le_supp_combo, 128, 64);
  gtk_widget_set_size_request (le_supp_combo, 189, 29);

  image2 = create_pixmap (le_supprimer, "delete.png");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed16), image2, 360, 0);
  gtk_widget_set_size_request (image2, 104, 152);

  le_btn_supp = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (le_btn_supp);
  gtk_fixed_put (GTK_FIXED (fixed16), le_btn_supp, 184, 104);
  gtk_widget_set_size_request (le_btn_supp, 104, 32);

  g_signal_connect ((gpointer) le_btn_supp, "clicked",
                    G_CALLBACK (on_le_btn_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (le_supprimer, le_supprimer, "le_supprimer");
  GLADE_HOOKUP_OBJECT (le_supprimer, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (le_supprimer, label24, "label24");
  GLADE_HOOKUP_OBJECT (le_supprimer, label23, "label23");
  GLADE_HOOKUP_OBJECT (le_supprimer, le_supp_ret_btn, "le_supp_ret_btn");
  GLADE_HOOKUP_OBJECT (le_supprimer, le_supp_combo, "le_supp_combo");
  GLADE_HOOKUP_OBJECT (le_supprimer, image2, "image2");
  GLADE_HOOKUP_OBJECT (le_supprimer, le_btn_supp, "le_btn_supp");

  return le_supprimer;
}

GtkWidget*
create_le_modifier (void)
{
  GtkWidget *le_modifier;
  GtkWidget *fixed12;
  GtkWidget *button26;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *le_modif_combo;
  GtkWidget *image4;
  GtkWidget *le_modif_btn;

  le_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (le_modifier), _("Modifier"));
  gtk_window_set_position (GTK_WINDOW (le_modifier), GTK_WIN_POS_CENTER);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (le_modifier), fixed12);

  button26 = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed12), button26, 8, 8);
  gtk_widget_set_size_request (button26, 56, 24);

  label20 = gtk_label_new (_("modifier une liste electorale"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed12), label20, 104, 8);
  gtk_widget_set_size_request (label20, 240, 24);

  label21 = gtk_label_new (_("Id "));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed12), label21, 64, 64);
  gtk_widget_set_size_request (label21, 56, 24);

  le_modif_combo = gtk_combo_box_entry_new_text ();
  gtk_widget_show (le_modif_combo);
  gtk_fixed_put (GTK_FIXED (fixed12), le_modif_combo, 128, 64);
  gtk_widget_set_size_request (le_modif_combo, 189, 29);

  image4 = create_pixmap (le_modifier, "resume.png");
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed12), image4, 328, 0);
  gtk_widget_set_size_request (image4, 136, 168);

  le_modif_btn = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (le_modif_btn);
  gtk_fixed_put (GTK_FIXED (fixed12), le_modif_btn, 208, 104);
  gtk_widget_set_size_request (le_modif_btn, 104, 32);

  g_signal_connect ((gpointer) le_modif_btn, "clicked",
                    G_CALLBACK (on_le_modif_btn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (le_modifier, le_modifier, "le_modifier");
  GLADE_HOOKUP_OBJECT (le_modifier, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (le_modifier, button26, "button26");
  GLADE_HOOKUP_OBJECT (le_modifier, label20, "label20");
  GLADE_HOOKUP_OBJECT (le_modifier, label21, "label21");
  GLADE_HOOKUP_OBJECT (le_modifier, le_modif_combo, "le_modif_combo");
  GLADE_HOOKUP_OBJECT (le_modifier, image4, "image4");
  GLADE_HOOKUP_OBJECT (le_modifier, le_modif_btn, "le_modif_btn");

  return le_modifier;
}

GtkWidget*
create_le_affichage (void)
{
  GtkWidget *le_affichage;
  GtkWidget *fixed15;
  GtkWidget *le_aff_treev;
  GtkWidget *le_aff_search;
  GtkWidget *le_aff_search_btn;
  GtkWidget *le_aff_ret;
  GtkWidget *image3;

  le_affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (le_affichage), _("le_affichage"));
  gtk_window_set_position (GTK_WINDOW (le_affichage), GTK_WIN_POS_CENTER);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (le_affichage), fixed15);

  le_aff_treev = gtk_tree_view_new ();
  gtk_widget_show (le_aff_treev);
  gtk_fixed_put (GTK_FIXED (fixed15), le_aff_treev, 24, 72);
  gtk_widget_set_size_request (le_aff_treev, 520, 192);

  le_aff_search = gtk_entry_new ();
  gtk_widget_show (le_aff_search);
  gtk_fixed_put (GTK_FIXED (fixed15), le_aff_search, 120, 24);
  gtk_widget_set_size_request (le_aff_search, 280, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (le_aff_search), 8226);

  le_aff_search_btn = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (le_aff_search_btn);
  gtk_fixed_put (GTK_FIXED (fixed15), le_aff_search_btn, 416, 24);
  gtk_widget_set_size_request (le_aff_search_btn, 120, 24);

  le_aff_ret = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (le_aff_ret);
  gtk_fixed_put (GTK_FIXED (fixed15), le_aff_ret, 32, 24);
  gtk_widget_set_size_request (le_aff_ret, 74, 29);

  image3 = create_pixmap (le_affichage, "searchLe.png");
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed15), image3, 560, 0);
  gtk_widget_set_size_request (image3, 296, 288);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (le_affichage, le_affichage, "le_affichage");
  GLADE_HOOKUP_OBJECT (le_affichage, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (le_affichage, le_aff_treev, "le_aff_treev");
  GLADE_HOOKUP_OBJECT (le_affichage, le_aff_search, "le_aff_search");
  GLADE_HOOKUP_OBJECT (le_affichage, le_aff_search_btn, "le_aff_search_btn");
  GLADE_HOOKUP_OBJECT (le_affichage, le_aff_ret, "le_aff_ret");
  GLADE_HOOKUP_OBJECT (le_affichage, image3, "image3");

  return le_affichage;
}

GtkWidget*
create_user (void)
{
  GtkWidget *user;
  GtkWidget *fixed17;
  GtkWidget *user_ajout_btn;
  GtkWidget *user_suppr_btn;
  GtkWidget *user_aff_btn;
  GtkWidget *user_modif_btn;

  user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (user), _("user"));
  gtk_window_set_position (GTK_WINDOW (user), GTK_WIN_POS_CENTER);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (user), fixed17);

  user_ajout_btn = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (user_ajout_btn);
  gtk_fixed_put (GTK_FIXED (fixed17), user_ajout_btn, 56, 72);
  gtk_widget_set_size_request (user_ajout_btn, 120, 40);

  user_suppr_btn = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (user_suppr_btn);
  gtk_fixed_put (GTK_FIXED (fixed17), user_suppr_btn, 56, 120);
  gtk_widget_set_size_request (user_suppr_btn, 120, 40);

  user_aff_btn = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (user_aff_btn);
  gtk_fixed_put (GTK_FIXED (fixed17), user_aff_btn, 56, 168);
  gtk_widget_set_size_request (user_aff_btn, 120, 40);

  user_modif_btn = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (user_modif_btn);
  gtk_fixed_put (GTK_FIXED (fixed17), user_modif_btn, 56, 216);
  gtk_widget_set_size_request (user_modif_btn, 120, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (user, user, "user");
  GLADE_HOOKUP_OBJECT (user, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (user, user_ajout_btn, "user_ajout_btn");
  GLADE_HOOKUP_OBJECT (user, user_suppr_btn, "user_suppr_btn");
  GLADE_HOOKUP_OBJECT (user, user_aff_btn, "user_aff_btn");
  GLADE_HOOKUP_OBJECT (user, user_modif_btn, "user_modif_btn");

  return user;
}

GtkWidget*
create_User_ajout (void)
{
  GtkWidget *User_ajout;
  GtkWidget *fixed18;
  GtkWidget *user_ajout_cin;
  GtkWidget *user_ajout_nom;
  GtkWidget *user_ajout_prenom;
  GtkObject *user_spinbutton6_adj;
  GtkWidget *user_spinbutton6;
  GtkObject *user_spinbutton7_adj;
  GtkWidget *user_spinbutton7;
  GtkObject *user_spinbutton8_adj;
  GtkWidget *user_spinbutton8;
  GtkWidget *entry13;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *user_ajout_sexe1;
  GSList *user_ajout_sexe1_group = NULL;
  GtkWidget *user_ajout_sexe2;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *user_ajout_login;
  GtkWidget *label35;
  GtkWidget *user_ajout_passe;
  GtkWidget *comboboxentry4;
  GtkWidget *label36;
  GtkWidget *entry16;
  GtkWidget *button38;
  GtkWidget *button39;
  GtkWidget *ajoute;
  GtkWidget *image12;

  User_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (User_ajout), _("user_ajout"));
  gtk_window_set_position (GTK_WINDOW (User_ajout), GTK_WIN_POS_CENTER);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (User_ajout), fixed18);

  user_ajout_cin = gtk_entry_new ();
  gtk_widget_show (user_ajout_cin);
  gtk_fixed_put (GTK_FIXED (fixed18), user_ajout_cin, 160, 48);
  gtk_widget_set_size_request (user_ajout_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (user_ajout_cin), 8226);

  user_ajout_nom = gtk_entry_new ();
  gtk_widget_show (user_ajout_nom);
  gtk_fixed_put (GTK_FIXED (fixed18), user_ajout_nom, 160, 96);
  gtk_widget_set_size_request (user_ajout_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (user_ajout_nom), 8226);

  user_ajout_prenom = gtk_entry_new ();
  gtk_widget_show (user_ajout_prenom);
  gtk_fixed_put (GTK_FIXED (fixed18), user_ajout_prenom, 448, 96);
  gtk_widget_set_size_request (user_ajout_prenom, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (user_ajout_prenom), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (user_ajout_prenom), 8226);

  user_spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  user_spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (user_spinbutton6_adj), 1, 0);
  gtk_widget_show (user_spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed18), user_spinbutton6, 224, 144);
  gtk_widget_set_size_request (user_spinbutton6, 60, 27);

  user_spinbutton7_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  user_spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (user_spinbutton7_adj), 1, 0);
  gtk_widget_show (user_spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed18), user_spinbutton7, 312, 144);
  gtk_widget_set_size_request (user_spinbutton7, 60, 27);

  user_spinbutton8_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  user_spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (user_spinbutton8_adj), 1, 0);
  gtk_widget_show (user_spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed18), user_spinbutton8, 424, 144);
  gtk_widget_set_size_request (user_spinbutton8, 72, 24);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed18), entry13, 160, 240);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  label27 = gtk_label_new (_("CIN:"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed18), label27, 48, 56);
  gtk_widget_set_size_request (label27, 80, 24);

  label28 = gtk_label_new (_("Nom: "));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed18), label28, 48, 96);
  gtk_widget_set_size_request (label28, 96, 32);

  label29 = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed18), label29, 368, 96);
  gtk_widget_set_size_request (label29, 88, 32);

  label30 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed18), label30, 72, 144);
  gtk_widget_set_size_request (label30, 136, 24);

  label31 = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed18), label31, 56, 192);
  gtk_widget_set_size_request (label31, 80, 24);

  user_ajout_sexe1 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (user_ajout_sexe1);
  gtk_fixed_put (GTK_FIXED (fixed18), user_ajout_sexe1, 136, 192);
  gtk_widget_set_size_request (user_ajout_sexe1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (user_ajout_sexe1), user_ajout_sexe1_group);
  user_ajout_sexe1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (user_ajout_sexe1));

  user_ajout_sexe2 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (user_ajout_sexe2);
  gtk_fixed_put (GTK_FIXED (fixed18), user_ajout_sexe2, 264, 192);
  gtk_widget_set_size_request (user_ajout_sexe2, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (user_ajout_sexe2), user_ajout_sexe1_group);
  user_ajout_sexe1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (user_ajout_sexe2));

  label32 = gtk_label_new (_("lieu:"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed18), label32, 56, 240);
  gtk_widget_set_size_request (label32, 72, 32);

  label33 = gtk_label_new (_("Role:"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed18), label33, 56, 296);
  gtk_widget_set_size_request (label33, 72, 24);

  label34 = gtk_label_new (_("Login:"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed18), label34, 56, 344);
  gtk_widget_set_size_request (label34, 80, 24);

  user_ajout_login = gtk_entry_new ();
  gtk_widget_show (user_ajout_login);
  gtk_fixed_put (GTK_FIXED (fixed18), user_ajout_login, 160, 336);
  gtk_widget_set_size_request (user_ajout_login, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (user_ajout_login), 8226);

  label35 = gtk_label_new (_("mot de passe:"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed18), label35, 368, 336);
  gtk_widget_set_size_request (label35, 144, 32);

  user_ajout_passe = gtk_entry_new ();
  gtk_widget_show (user_ajout_passe);
  gtk_fixed_put (GTK_FIXED (fixed18), user_ajout_passe, 504, 336);
  gtk_widget_set_size_request (user_ajout_passe, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (user_ajout_passe), 8226);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed18), comboboxentry4, 160, 288);
  gtk_widget_set_size_request (comboboxentry4, 189, 29);

  label36 = gtk_label_new (_("num BV:"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed18), label36, 56, 392);
  gtk_widget_set_size_request (label36, 96, 32);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed18), entry16, 160, 392);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  button38 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button38);
  gtk_fixed_put (GTK_FIXED (fixed18), button38, 424, 416);
  gtk_widget_set_size_request (button38, 128, 40);

  button39 = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (button39);
  gtk_fixed_put (GTK_FIXED (fixed18), button39, 16, 8);
  gtk_widget_set_size_request (button39, 56, 24);

  ajoute = gtk_label_new (_("ajouter "));
  gtk_widget_show (ajoute);
  gtk_fixed_put (GTK_FIXED (fixed18), ajoute, 176, 0);
  gtk_widget_set_size_request (ajoute, 216, 32);

  image12 = create_pixmap (User_ajout, "images.png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed18), image12, 144, 464);
  gtk_widget_set_size_request (image12, 408, 272);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (User_ajout, User_ajout, "User_ajout");
  GLADE_HOOKUP_OBJECT (User_ajout, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (User_ajout, user_ajout_cin, "user_ajout_cin");
  GLADE_HOOKUP_OBJECT (User_ajout, user_ajout_nom, "user_ajout_nom");
  GLADE_HOOKUP_OBJECT (User_ajout, user_ajout_prenom, "user_ajout_prenom");
  GLADE_HOOKUP_OBJECT (User_ajout, user_spinbutton6, "user_spinbutton6");
  GLADE_HOOKUP_OBJECT (User_ajout, user_spinbutton7, "user_spinbutton7");
  GLADE_HOOKUP_OBJECT (User_ajout, user_spinbutton8, "user_spinbutton8");
  GLADE_HOOKUP_OBJECT (User_ajout, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (User_ajout, label27, "label27");
  GLADE_HOOKUP_OBJECT (User_ajout, label28, "label28");
  GLADE_HOOKUP_OBJECT (User_ajout, label29, "label29");
  GLADE_HOOKUP_OBJECT (User_ajout, label30, "label30");
  GLADE_HOOKUP_OBJECT (User_ajout, label31, "label31");
  GLADE_HOOKUP_OBJECT (User_ajout, user_ajout_sexe1, "user_ajout_sexe1");
  GLADE_HOOKUP_OBJECT (User_ajout, user_ajout_sexe2, "user_ajout_sexe2");
  GLADE_HOOKUP_OBJECT (User_ajout, label32, "label32");
  GLADE_HOOKUP_OBJECT (User_ajout, label33, "label33");
  GLADE_HOOKUP_OBJECT (User_ajout, label34, "label34");
  GLADE_HOOKUP_OBJECT (User_ajout, user_ajout_login, "user_ajout_login");
  GLADE_HOOKUP_OBJECT (User_ajout, label35, "label35");
  GLADE_HOOKUP_OBJECT (User_ajout, user_ajout_passe, "user_ajout_passe");
  GLADE_HOOKUP_OBJECT (User_ajout, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (User_ajout, label36, "label36");
  GLADE_HOOKUP_OBJECT (User_ajout, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (User_ajout, button38, "button38");
  GLADE_HOOKUP_OBJECT (User_ajout, button39, "button39");
  GLADE_HOOKUP_OBJECT (User_ajout, ajoute, "ajoute");
  GLADE_HOOKUP_OBJECT (User_ajout, image12, "image12");

  return User_ajout;
}

GtkWidget*
create_user_affichage (void)
{
  GtkWidget *user_affichage;
  GtkWidget *fixed19;
  GtkWidget *treeview2;
  GtkWidget *button41;

  user_affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (user_affichage), _("window15"));
  gtk_window_set_position (GTK_WINDOW (user_affichage), GTK_WIN_POS_CENTER);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (user_affichage), fixed19);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed19), treeview2, 24, 24);
  gtk_widget_set_size_request (treeview2, 360, 200);

  button41 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button41);
  gtk_fixed_put (GTK_FIXED (fixed19), button41, 24, 248);
  gtk_widget_set_size_request (button41, 74, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (user_affichage, user_affichage, "user_affichage");
  GLADE_HOOKUP_OBJECT (user_affichage, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (user_affichage, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (user_affichage, button41, "button41");

  return user_affichage;
}

GtkWidget*
create_user_supprimer (void)
{
  GtkWidget *user_supprimer;
  GtkWidget *fixed22;
  GtkWidget *button44;
  GtkWidget *label40;
  GtkWidget *label39;
  GtkWidget *user_supp_btn;
  GtkWidget *user_supp_combo;
  GtkWidget *image11;

  user_supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (user_supprimer), _("Supprimer"));
  gtk_window_set_position (GTK_WINDOW (user_supprimer), GTK_WIN_POS_CENTER);

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (user_supprimer), fixed22);

  button44 = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (button44);
  gtk_fixed_put (GTK_FIXED (fixed22), button44, 8, 8);
  gtk_widget_set_size_request (button44, 56, 24);

  label40 = gtk_label_new (_("supprimer "));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed22), label40, 104, 8);
  gtk_widget_set_size_request (label40, 240, 24);

  label39 = gtk_label_new (_("cin:"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed22), label39, 64, 64);
  gtk_widget_set_size_request (label39, 56, 24);

  user_supp_btn = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (user_supp_btn);
  gtk_fixed_put (GTK_FIXED (fixed22), user_supp_btn, 184, 104);
  gtk_widget_set_size_request (user_supp_btn, 104, 32);

  user_supp_combo = gtk_combo_box_entry_new_text ();
  gtk_widget_show (user_supp_combo);
  gtk_fixed_put (GTK_FIXED (fixed22), user_supp_combo, 128, 64);
  gtk_widget_set_size_request (user_supp_combo, 189, 29);

  image11 = create_pixmap (user_supprimer, "delete.png");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed22), image11, 344, 0);
  gtk_widget_set_size_request (image11, 176, 152);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (user_supprimer, user_supprimer, "user_supprimer");
  GLADE_HOOKUP_OBJECT (user_supprimer, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (user_supprimer, button44, "button44");
  GLADE_HOOKUP_OBJECT (user_supprimer, label40, "label40");
  GLADE_HOOKUP_OBJECT (user_supprimer, label39, "label39");
  GLADE_HOOKUP_OBJECT (user_supprimer, user_supp_btn, "user_supp_btn");
  GLADE_HOOKUP_OBJECT (user_supprimer, user_supp_combo, "user_supp_combo");
  GLADE_HOOKUP_OBJECT (user_supprimer, image11, "image11");

  return user_supprimer;
}

GtkWidget*
create_user_modifier (void)
{
  GtkWidget *user_modifier;
  GtkWidget *fixed23;
  GtkWidget *button46;
  GtkWidget *label42;
  GtkWidget *label41;
  GtkWidget *user_modif_combo;
  GtkWidget *user_modif_btn;

  user_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (user_modifier), _("user_modifier"));
  gtk_window_set_position (GTK_WINDOW (user_modifier), GTK_WIN_POS_CENTER);

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (user_modifier), fixed23);

  button46 = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (button46);
  gtk_fixed_put (GTK_FIXED (fixed23), button46, 8, 8);
  gtk_widget_set_size_request (button46, 56, 24);

  label42 = gtk_label_new (_("cin:"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed23), label42, 64, 64);
  gtk_widget_set_size_request (label42, 56, 24);

  label41 = gtk_label_new (_("modifier "));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed23), label41, 104, 8);
  gtk_widget_set_size_request (label41, 240, 24);

  user_modif_combo = gtk_combo_box_entry_new_text ();
  gtk_widget_show (user_modif_combo);
  gtk_fixed_put (GTK_FIXED (fixed23), user_modif_combo, 128, 64);
  gtk_widget_set_size_request (user_modif_combo, 189, 29);

  user_modif_btn = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (user_modif_btn);
  gtk_fixed_put (GTK_FIXED (fixed23), user_modif_btn, 184, 104);
  gtk_widget_set_size_request (user_modif_btn, 104, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (user_modifier, user_modifier, "user_modifier");
  GLADE_HOOKUP_OBJECT (user_modifier, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (user_modifier, button46, "button46");
  GLADE_HOOKUP_OBJECT (user_modifier, label42, "label42");
  GLADE_HOOKUP_OBJECT (user_modifier, label41, "label41");
  GLADE_HOOKUP_OBJECT (user_modifier, user_modif_combo, "user_modif_combo");
  GLADE_HOOKUP_OBJECT (user_modifier, user_modif_btn, "user_modif_btn");

  return user_modifier;
}

GtkWidget*
create_ObsAjout (void)
{
  GtkWidget *ObsAjout;
  GtkWidget *fixed24;
  GtkWidget *obs_aj_id;
  GtkWidget *entry24;
  GtkWidget *entry25;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkWidget *labelID;
  GtkWidget *label56;
  GtkWidget *labelPrenom;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *buttonAjout;
  GtkWidget *radiobutton12;
  GSList *radiobutton12_group = NULL;
  GtkWidget *radiobutton13;
  GtkWidget *comboboxentry8;
  GtkWidget *comboboxentry9;

  ObsAjout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ObsAjout), _("window19"));
  gtk_window_set_position (GTK_WINDOW (ObsAjout), GTK_WIN_POS_CENTER);

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (ObsAjout), fixed24);

  obs_aj_id = gtk_entry_new ();
  gtk_widget_show (obs_aj_id);
  gtk_fixed_put (GTK_FIXED (fixed24), obs_aj_id, 192, 40);
  gtk_widget_set_size_request (obs_aj_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (obs_aj_id), 8226);

  entry24 = gtk_entry_new ();
  gtk_widget_show (entry24);
  gtk_fixed_put (GTK_FIXED (fixed24), entry24, 192, 96);
  gtk_widget_set_size_request (entry24, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24), 8226);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_fixed_put (GTK_FIXED (fixed24), entry25, 488, 96);
  gtk_widget_set_size_request (entry25, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  spinbutton12_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed24), spinbutton12, 240, 296);
  gtk_widget_set_size_request (spinbutton12, 60, 27);

  labelID = gtk_label_new (_("ID:"));
  gtk_widget_show (labelID);
  gtk_fixed_put (GTK_FIXED (fixed24), labelID, 112, 40);
  gtk_widget_set_size_request (labelID, 48, 32);

  label56 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed24), label56, 120, 96);
  gtk_widget_set_size_request (label56, 56, 24);

  labelPrenom = gtk_label_new (_("Prenom:"));
  gtk_widget_show (labelPrenom);
  gtk_fixed_put (GTK_FIXED (fixed24), labelPrenom, 392, 88);
  gtk_widget_set_size_request (labelPrenom, 80, 32);

  label58 = gtk_label_new (_("Nationalite:"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed24), label58, 120, 152);
  gtk_widget_set_size_request (label58, 88, 33);

  label59 = gtk_label_new (_("Appartenance:"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed24), label59, 120, 208);
  gtk_widget_set_size_request (label59, 112, 32);

  label60 = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed24), label60, 112, 256);
  gtk_widget_set_size_request (label60, 64, 25);

  label61 = gtk_label_new (_("numero BV:"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed24), label61, 120, 296);
  gtk_widget_set_size_request (label61, 96, 32);

  buttonAjout = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonAjout);
  gtk_fixed_put (GTK_FIXED (fixed24), buttonAjout, 216, 376);
  gtk_widget_set_size_request (buttonAjout, 74, 29);

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton12);
  gtk_fixed_put (GTK_FIXED (fixed24), radiobutton12, 224, 256);
  gtk_widget_set_size_request (radiobutton12, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton12_group);
  radiobutton12_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  radiobutton13 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton13);
  gtk_fixed_put (GTK_FIXED (fixed24), radiobutton13, 392, 256);
  gtk_widget_set_size_request (radiobutton13, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton13), radiobutton12_group);
  radiobutton12_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton13));

  comboboxentry8 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry8);
  gtk_fixed_put (GTK_FIXED (fixed24), comboboxentry8, 240, 152);
  gtk_widget_set_size_request (comboboxentry8, 189, 29);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxentry8), 2);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Tunisienne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("fran\303\247aise"));

  comboboxentry9 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry9);
  gtk_fixed_put (GTK_FIXED (fixed24), comboboxentry9, 240, 208);
  gtk_widget_set_size_request (comboboxentry9, 189, 29);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxentry9), 3);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("Presse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("Hote"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("societe civile"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ObsAjout, ObsAjout, "ObsAjout");
  GLADE_HOOKUP_OBJECT (ObsAjout, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (ObsAjout, obs_aj_id, "obs_aj_id");
  GLADE_HOOKUP_OBJECT (ObsAjout, entry24, "entry24");
  GLADE_HOOKUP_OBJECT (ObsAjout, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (ObsAjout, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (ObsAjout, labelID, "labelID");
  GLADE_HOOKUP_OBJECT (ObsAjout, label56, "label56");
  GLADE_HOOKUP_OBJECT (ObsAjout, labelPrenom, "labelPrenom");
  GLADE_HOOKUP_OBJECT (ObsAjout, label58, "label58");
  GLADE_HOOKUP_OBJECT (ObsAjout, label59, "label59");
  GLADE_HOOKUP_OBJECT (ObsAjout, label60, "label60");
  GLADE_HOOKUP_OBJECT (ObsAjout, label61, "label61");
  GLADE_HOOKUP_OBJECT (ObsAjout, buttonAjout, "buttonAjout");
  GLADE_HOOKUP_OBJECT (ObsAjout, radiobutton12, "radiobutton12");
  GLADE_HOOKUP_OBJECT (ObsAjout, radiobutton13, "radiobutton13");
  GLADE_HOOKUP_OBJECT (ObsAjout, comboboxentry8, "comboboxentry8");
  GLADE_HOOKUP_OBJECT (ObsAjout, comboboxentry9, "comboboxentry9");

  return ObsAjout;
}

GtkWidget*
create_Obs (void)
{
  GtkWidget *Obs;
  GtkWidget *fixed25;
  GtkWidget *button51;
  GtkWidget *button52;
  GtkWidget *button53;

  Obs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Obs), _("Observateur"));
  gtk_window_set_position (GTK_WINDOW (Obs), GTK_WIN_POS_CENTER);

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (Obs), fixed25);

  button51 = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (button51);
  gtk_fixed_put (GTK_FIXED (fixed25), button51, 56, 72);
  gtk_widget_set_size_request (button51, 120, 40);

  button52 = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button52);
  gtk_fixed_put (GTK_FIXED (fixed25), button52, 56, 120);
  gtk_widget_set_size_request (button52, 120, 40);

  button53 = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button53);
  gtk_fixed_put (GTK_FIXED (fixed25), button53, 56, 168);
  gtk_widget_set_size_request (button53, 120, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Obs, Obs, "Obs");
  GLADE_HOOKUP_OBJECT (Obs, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (Obs, button51, "button51");
  GLADE_HOOKUP_OBJECT (Obs, button52, "button52");
  GLADE_HOOKUP_OBJECT (Obs, button53, "button53");

  return Obs;
}

GtkWidget*
create_ObsAffiche (void)
{
  GtkWidget *ObsAffiche;
  GtkWidget *fixed26;
  GtkWidget *treeview3;
  GtkWidget *button62;

  ObsAffiche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ObsAffiche), _("window21"));
  gtk_window_set_position (GTK_WINDOW (ObsAffiche), GTK_WIN_POS_CENTER);

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_container_add (GTK_CONTAINER (ObsAffiche), fixed26);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed26), treeview3, 56, 48);
  gtk_widget_set_size_request (treeview3, 360, 200);

  button62 = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (button62);
  gtk_fixed_put (GTK_FIXED (fixed26), button62, 16, 8);
  gtk_widget_set_size_request (button62, 64, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ObsAffiche, ObsAffiche, "ObsAffiche");
  GLADE_HOOKUP_OBJECT (ObsAffiche, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (ObsAffiche, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (ObsAffiche, button62, "button62");

  return ObsAffiche;
}

GtkWidget*
create_ObsSupprimer (void)
{
  GtkWidget *ObsSupprimer;
  GtkWidget *fixed27;
  GtkWidget *button55;
  GtkWidget *button56;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *comboboxentry10;

  ObsSupprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ObsSupprimer), _("Supprimer"));
  gtk_window_set_position (GTK_WINDOW (ObsSupprimer), GTK_WIN_POS_CENTER);

  fixed27 = gtk_fixed_new ();
  gtk_widget_show (fixed27);
  gtk_container_add (GTK_CONTAINER (ObsSupprimer), fixed27);

  button55 = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (button55);
  gtk_fixed_put (GTK_FIXED (fixed27), button55, 8, 8);
  gtk_widget_set_size_request (button55, 56, 24);

  button56 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button56);
  gtk_fixed_put (GTK_FIXED (fixed27), button56, 184, 104);
  gtk_widget_set_size_request (button56, 104, 32);

  label62 = gtk_label_new (_("supprimer "));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed27), label62, 104, 8);
  gtk_widget_set_size_request (label62, 240, 24);

  label63 = gtk_label_new (_("ID:"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed27), label63, 64, 64);
  gtk_widget_set_size_request (label63, 56, 24);

  comboboxentry10 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry10);
  gtk_fixed_put (GTK_FIXED (fixed27), comboboxentry10, 128, 64);
  gtk_widget_set_size_request (comboboxentry10, 189, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ObsSupprimer, ObsSupprimer, "ObsSupprimer");
  GLADE_HOOKUP_OBJECT (ObsSupprimer, fixed27, "fixed27");
  GLADE_HOOKUP_OBJECT (ObsSupprimer, button55, "button55");
  GLADE_HOOKUP_OBJECT (ObsSupprimer, button56, "button56");
  GLADE_HOOKUP_OBJECT (ObsSupprimer, label62, "label62");
  GLADE_HOOKUP_OBJECT (ObsSupprimer, label63, "label63");
  GLADE_HOOKUP_OBJECT (ObsSupprimer, comboboxentry10, "comboboxentry10");

  return ObsSupprimer;
}

GtkWidget*
create_GE_supprimer (void)
{
  GtkWidget *GE_supprimer;
  GtkWidget *fixed28;
  GtkWidget *fixed29;
  GtkWidget *entryId;
  GtkWidget *butSupp;
  GtkWidget *labelId;
  GtkWidget *butQuit;
  GtkWidget *label68;

  GE_supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GE_supprimer), _("Supprimer"));
  gtk_window_set_position (GTK_WINDOW (GE_supprimer), GTK_WIN_POS_CENTER);

  fixed28 = gtk_fixed_new ();
  gtk_widget_show (fixed28);
  gtk_container_add (GTK_CONTAINER (GE_supprimer), fixed28);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_fixed_put (GTK_FIXED (fixed28), fixed29, 176, 40);
  gtk_widget_set_size_request (fixed29, 0, 0);

  entryId = gtk_entry_new ();
  gtk_widget_show (entryId);
  gtk_fixed_put (GTK_FIXED (fixed29), entryId, 136, 56);
  gtk_widget_set_size_request (entryId, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryId), 8226);

  butSupp = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (butSupp);
  gtk_fixed_put (GTK_FIXED (fixed29), butSupp, 152, 112);
  gtk_widget_set_size_request (butSupp, 98, 29);

  labelId = gtk_label_new (_("CIN :"));
  gtk_widget_show (labelId);
  gtk_fixed_put (GTK_FIXED (fixed29), labelId, 48, 48);
  gtk_widget_set_size_request (labelId, 88, 48);

  butQuit = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (butQuit);
  gtk_fixed_put (GTK_FIXED (fixed29), butQuit, 0, 0);
  gtk_widget_set_size_request (butQuit, 48, 24);

  label68 = gtk_label_new (_("Supprimer une election"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed28), label68, 264, 16);
  gtk_widget_set_size_request (label68, 224, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GE_supprimer, GE_supprimer, "GE_supprimer");
  GLADE_HOOKUP_OBJECT (GE_supprimer, fixed28, "fixed28");
  GLADE_HOOKUP_OBJECT (GE_supprimer, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (GE_supprimer, entryId, "entryId");
  GLADE_HOOKUP_OBJECT (GE_supprimer, butSupp, "butSupp");
  GLADE_HOOKUP_OBJECT (GE_supprimer, labelId, "labelId");
  GLADE_HOOKUP_OBJECT (GE_supprimer, butQuit, "butQuit");
  GLADE_HOOKUP_OBJECT (GE_supprimer, label68, "label68");

  return GE_supprimer;
}

GtkWidget*
create_GE_modifier (void)
{
  GtkWidget *GE_modifier;
  GtkWidget *fixed30;
  GtkWidget *fixed31;
  GtkWidget *button61;
  GtkWidget *entryId;
  GtkWidget *labelId;
  GtkWidget *butModifier;
  GtkWidget *label69;

  GE_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GE_modifier), _("modifer"));
  gtk_window_set_position (GTK_WINDOW (GE_modifier), GTK_WIN_POS_CENTER);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_container_add (GTK_CONTAINER (GE_modifier), fixed30);

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_fixed_put (GTK_FIXED (fixed30), fixed31, 0, 0);
  gtk_widget_set_size_request (fixed31, 400, 168);

  button61 = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (button61);
  gtk_fixed_put (GTK_FIXED (fixed31), button61, 8, 8);
  gtk_widget_set_size_request (button61, 56, 24);

  entryId = gtk_entry_new ();
  gtk_widget_show (entryId);
  gtk_fixed_put (GTK_FIXED (fixed31), entryId, 128, 56);
  gtk_widget_set_size_request (entryId, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryId), 8226);

  labelId = gtk_label_new (_("Id :"));
  gtk_widget_show (labelId);
  gtk_fixed_put (GTK_FIXED (fixed31), labelId, 72, 48);
  gtk_widget_set_size_request (labelId, 56, 40);

  butModifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (butModifier);
  gtk_fixed_put (GTK_FIXED (fixed31), butModifier, 160, 112);
  gtk_widget_set_size_request (butModifier, 104, 32);

  label69 = gtk_label_new (_("Modifier une election"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed31), label69, 136, 16);
  gtk_widget_set_size_request (label69, 184, 16);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GE_modifier, GE_modifier, "GE_modifier");
  GLADE_HOOKUP_OBJECT (GE_modifier, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (GE_modifier, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (GE_modifier, button61, "button61");
  GLADE_HOOKUP_OBJECT (GE_modifier, entryId, "entryId");
  GLADE_HOOKUP_OBJECT (GE_modifier, labelId, "labelId");
  GLADE_HOOKUP_OBJECT (GE_modifier, butModifier, "butModifier");
  GLADE_HOOKUP_OBJECT (GE_modifier, label69, "label69");

  return GE_modifier;
}

GtkWidget*
create_auth (void)
{
  GtkWidget *auth;
  GtkWidget *fixed33;
  GtkWidget *auth_id;
  GtkWidget *auth_pass;
  GtkWidget *eventbox7;
  GtkWidget *label64;
  GtkWidget *eventbox8;
  GtkWidget *label65;
  GtkWidget *eventbox9;
  GtkWidget *label66;
  GtkWidget *image8;

  auth = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (auth), _("Authentication"));
  gtk_window_set_position (GTK_WINDOW (auth), GTK_WIN_POS_CENTER);

  fixed33 = gtk_fixed_new ();
  gtk_widget_show (fixed33);
  gtk_container_add (GTK_CONTAINER (auth), fixed33);

  auth_id = gtk_entry_new ();
  gtk_widget_show (auth_id);
  gtk_fixed_put (GTK_FIXED (fixed33), auth_id, 176, 120);
  gtk_widget_set_size_request (auth_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (auth_id), 8226);

  auth_pass = gtk_entry_new ();
  gtk_widget_show (auth_pass);
  gtk_fixed_put (GTK_FIXED (fixed33), auth_pass, 184, 192);
  gtk_widget_set_size_request (auth_pass, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (auth_pass), 8226);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_fixed_put (GTK_FIXED (fixed33), eventbox7, 168, 24);
  gtk_widget_set_size_request (eventbox7, 168, 24);

  label64 = gtk_label_new (_("Authentication"));
  gtk_widget_show (label64);
  gtk_container_add (GTK_CONTAINER (eventbox7), label64);
  gtk_widget_set_size_request (label64, 168, 24);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed33), eventbox8, 88, 120);
  gtk_widget_set_size_request (eventbox8, 49, 17);

  label65 = gtk_label_new (_("Id"));
  gtk_widget_show (label65);
  gtk_container_add (GTK_CONTAINER (eventbox8), label65);
  gtk_widget_set_size_request (label65, 49, 17);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed33), eventbox9, 64, 200);
  gtk_widget_set_size_request (eventbox9, 81, 17);

  label66 = gtk_label_new (_("Password"));
  gtk_widget_show (label66);
  gtk_container_add (GTK_CONTAINER (eventbox9), label66);
  gtk_widget_set_size_request (label66, 81, 17);

  image8 = create_pixmap (auth, "istockphoto-1299730469-170667a.jpg");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed33), image8, 0, 0);
  gtk_widget_set_size_request (image8, 512, 328);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (auth, auth, "auth");
  GLADE_HOOKUP_OBJECT (auth, fixed33, "fixed33");
  GLADE_HOOKUP_OBJECT (auth, auth_id, "auth_id");
  GLADE_HOOKUP_OBJECT (auth, auth_pass, "auth_pass");
  GLADE_HOOKUP_OBJECT (auth, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (auth, label64, "label64");
  GLADE_HOOKUP_OBJECT (auth, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (auth, label65, "label65");
  GLADE_HOOKUP_OBJECT (auth, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (auth, label66, "label66");
  GLADE_HOOKUP_OBJECT (auth, image8, "image8");

  return auth;
}

GtkWidget*
create_gestion_admin (void)
{
  GtkWidget *gestion_admin;
  GtkWidget *eventbox12;
  GtkWidget *fixed35;
  GtkWidget *btn_gest_user;
  GtkWidget *btn_gest_le;
  GtkWidget *btn_gest_bv;

  gestion_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_admin), _("Admin"));
  gtk_window_set_position (GTK_WINDOW (gestion_admin), GTK_WIN_POS_CENTER);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_container_add (GTK_CONTAINER (gestion_admin), eventbox12);

  fixed35 = gtk_fixed_new ();
  gtk_widget_show (fixed35);
  gtk_container_add (GTK_CONTAINER (eventbox12), fixed35);

  btn_gest_user = gtk_button_new_with_mnemonic (_("Gestion des utilisateurs"));
  gtk_widget_show (btn_gest_user);
  gtk_fixed_put (GTK_FIXED (fixed35), btn_gest_user, 64, 40);
  gtk_widget_set_size_request (btn_gest_user, 240, 32);

  btn_gest_le = gtk_button_new_with_mnemonic (_("Gestion des elections"));
  gtk_widget_show (btn_gest_le);
  gtk_fixed_put (GTK_FIXED (fixed35), btn_gest_le, 64, 96);
  gtk_widget_set_size_request (btn_gest_le, 240, 32);

  btn_gest_bv = gtk_button_new_with_mnemonic (_("Gestion des bureaux de vote"));
  gtk_widget_show (btn_gest_bv);
  gtk_fixed_put (GTK_FIXED (fixed35), btn_gest_bv, 64, 152);
  gtk_widget_set_size_request (btn_gest_bv, 240, 29);

  g_signal_connect ((gpointer) btn_gest_le, "clicked",
                    G_CALLBACK (on_buttonElec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_admin, gestion_admin, "gestion_admin");
  GLADE_HOOKUP_OBJECT (gestion_admin, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (gestion_admin, fixed35, "fixed35");
  GLADE_HOOKUP_OBJECT (gestion_admin, btn_gest_user, "btn_gest_user");
  GLADE_HOOKUP_OBJECT (gestion_admin, btn_gest_le, "btn_gest_le");
  GLADE_HOOKUP_OBJECT (gestion_admin, btn_gest_bv, "btn_gest_bv");

  return gestion_admin;
}

GtkWidget*
create_GE_affichier (void)
{
  GtkWidget *GE_affichier;
  GtkWidget *fixed36;
  GtkWidget *treeview4;
  GtkWidget *button67;
  GtkWidget *entry26;
  GtkWidget *button68;

  GE_affichier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GE_affichier), _("Affichage"));
  gtk_window_set_position (GTK_WINDOW (GE_affichier), GTK_WIN_POS_CENTER);

  fixed36 = gtk_fixed_new ();
  gtk_widget_show (fixed36);
  gtk_container_add (GTK_CONTAINER (GE_affichier), fixed36);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed36), treeview4, 24, 72);
  gtk_widget_set_size_request (treeview4, 520, 192);

  button67 = gtk_button_new_with_mnemonic (_("<"));
  gtk_widget_show (button67);
  gtk_fixed_put (GTK_FIXED (fixed36), button67, 24, 24);
  gtk_widget_set_size_request (button67, 74, 29);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed36), entry26, 160, 24);
  gtk_widget_set_size_request (entry26, 240, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  button68 = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (button68);
  gtk_fixed_put (GTK_FIXED (fixed36), button68, 416, 24);
  gtk_widget_set_size_request (button68, 74, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GE_affichier, GE_affichier, "GE_affichier");
  GLADE_HOOKUP_OBJECT (GE_affichier, fixed36, "fixed36");
  GLADE_HOOKUP_OBJECT (GE_affichier, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (GE_affichier, button67, "button67");
  GLADE_HOOKUP_OBJECT (GE_affichier, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (GE_affichier, button68, "button68");

  return GE_affichier;
}

GtkWidget*
create_le_vote (void)
{
  GtkWidget *le_vote;
  GtkWidget *eventbox11;
  GtkWidget *fixed37;
  GtkWidget *label73;
  GtkWidget *le_vote_combo;
  GtkWidget *label74;
  GtkWidget *le_btn_vote_valider;
  GtkWidget *le_vote_blanche_btn;

  le_vote = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (le_vote), _("Voter"));
  gtk_window_set_position (GTK_WINDOW (le_vote), GTK_WIN_POS_CENTER);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_container_add (GTK_CONTAINER (le_vote), eventbox11);

  fixed37 = gtk_fixed_new ();
  gtk_widget_show (fixed37);
  gtk_container_add (GTK_CONTAINER (eventbox11), fixed37);

  label73 = gtk_label_new (_("Choisir une liste"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed37), label73, 40, 40);
  gtk_widget_set_size_request (label73, 136, 24);

  le_vote_combo = gtk_combo_box_entry_new_text ();
  gtk_widget_show (le_vote_combo);
  gtk_fixed_put (GTK_FIXED (fixed37), le_vote_combo, 176, 40);
  gtk_widget_set_size_request (le_vote_combo, 189, 29);

  label74 = gtk_label_new (_("Ou bien "));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed37), label74, 80, 88);
  gtk_widget_set_size_request (label74, 104, 17);

  le_btn_vote_valider = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (le_btn_vote_valider);
  gtk_fixed_put (GTK_FIXED (fixed37), le_btn_vote_valider, 384, 40);
  gtk_widget_set_size_request (le_btn_vote_valider, 74, 29);

  le_vote_blanche_btn = gtk_button_new_with_mnemonic (_("Faire une vote blanche"));
  gtk_widget_show (le_vote_blanche_btn);
  gtk_fixed_put (GTK_FIXED (fixed37), le_vote_blanche_btn, 176, 80);
  gtk_widget_set_size_request (le_vote_blanche_btn, 280, 29);

  g_signal_connect ((gpointer) le_btn_vote_valider, "clicked",
                    G_CALLBACK (on_le_btn_vote_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) le_vote_blanche_btn, "clicked",
                    G_CALLBACK (on_le_vote_blanche_btn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (le_vote, le_vote, "le_vote");
  GLADE_HOOKUP_OBJECT (le_vote, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (le_vote, fixed37, "fixed37");
  GLADE_HOOKUP_OBJECT (le_vote, label73, "label73");
  GLADE_HOOKUP_OBJECT (le_vote, le_vote_combo, "le_vote_combo");
  GLADE_HOOKUP_OBJECT (le_vote, label74, "label74");
  GLADE_HOOKUP_OBJECT (le_vote, le_btn_vote_valider, "le_btn_vote_valider");
  GLADE_HOOKUP_OBJECT (le_vote, le_vote_blanche_btn, "le_vote_blanche_btn");

  return le_vote;
}

