/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_entry (void);
GtkWidget* create_ge (void);
GtkWidget* create_ge_ajouter (void);
GtkWidget* create_bv (void);
GtkWidget* create_bv_ajout (void);
GtkWidget* create_bv_supprimer (void);
GtkWidget* create_bv_modifier (void);
GtkWidget* create_bv_affichage (void);
GtkWidget* create_le (void);
GtkWidget* create_le_ajout (void);
GtkWidget* create_le_supprimer (void);
GtkWidget* create_le_modifier (void);
GtkWidget* create_le_affichage (void);
GtkWidget* create_ObsAjout (void);
GtkWidget* create_Obs (void);
GtkWidget* create_auth (void);
GtkWidget* create_gestion_admin (void);
GtkWidget* create_le_vote (void);
GtkWidget* create_statistics (void);
GtkWidget* create_loading_window (void);
GtkWidget* create_ge_modifier (void);
GtkWidget* create_ge_supprimer (void);
GtkWidget* create_ge_affichier (void);
GtkWidget* create_aj (void);
GtkWidget* create_user (void);
GtkWidget* create_modif (void);
GtkWidget* create_aff (void);
